# Feature selection and data splitting for mds data 

In [26]:
%load_ext autoreload
%autoreload 2

import numpy as np
import polars as pl
from sklearn.model_selection import StratifiedKFold

from src.data_preprocessing import OmicDataSplitter

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
y = pl.read_csv("mds_data/preprocessed/annotations_66.csv")

y = (
    y.select("SAMPLE_ID", "disease")
    .rename({"SAMPLE_ID": "sample_ids", "disease": "class"})
    .with_columns(pl.col("class") - 1)
)
y

shape: (66, 2)
┌────────────┬───────┐
│ sample_ids ┆ class │
│ ---        ┆ ---   │
│ str        ┆ i64   │
╞════════════╪═══════╡
│ N58        ┆ 0     │
│ N60        ┆ 0     │
│ N70        ┆ 0     │
│ N82        ┆ 0     │
│ N83        ┆ 0     │
│ …          ┆ …     │
│ V806       ┆ 1     │
│ V839       ┆ 1     │
│ V883       ┆ 1     │
│ V888       ┆ 1     │
│ V940       ┆ 1     │
└────────────┴───────┘

In [3]:
mrna = pl.read_csv("mds_data/preprocessed/mrna.csv")

OmicDataSplitter(
    df=mrna,
    annotation_cols=["GENE_ID", "GENE_NAME"],
    y_df=y,
    n_features=200,
    n_splits=5,
    random_state=3,
    output_dir="mds_data/splits/mrna",
).process_data()

shape: (3_000, 68)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ GENE_ID   ┆ GENE_NAME ┆ N58       ┆ N60       ┆ … ┆ V839      ┆ V883      ┆ V888      ┆ V940     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ENSG00000 ┆ SEC14L5   ┆ 4.574155  ┆ 7.288239  ┆ … ┆ 3.976603  ┆ 5.670529  ┆ 4.456624  ┆ 4.897539 │
│ 103184    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ LGALSL    ┆ 7.455039  ┆ 8.479401  ┆ … ┆ 6.838144  ┆ 7.450425  ┆ 6.055094  ┆ 6.88753  │
│ 119862    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ IGFBP5    ┆ 1.531313  ┆ 4.93984   ┆ … ┆ 2.710774  ┆ 4.358541  ┆ 5.20171   ┆ 6.416449 │
│ 115461    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ THBS1     ┆ 10.787846 ┆ 12.452547 ┆ … ┆ 10.274893 ┆ 10.805033 ┆ 10.464737 ┆ 10.70489 │
│ 137801    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ ENSG00000 ┆ HPSE      ┆ 6.935416  ┆ 7.987946  ┆ … ┆ 7.451146  ┆ 6.940394  ┆ 6.860065  ┆ 6.735584 │
│ 173083    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ENSG00000 ┆ RBFOX2    ┆ 8.22931   ┆ 8.577745  ┆ … ┆ 7.52732   ┆ 7.067754  ┆ 7.545361  ┆ 6.655649 │
│ 100320    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ EPS8L1    ┆ 4.921367  ┆ 5.092288  ┆ … ┆ 4.054711  ┆ 4.791207  ┆ 4.437371  ┆ 4.463407 │
│ 131037    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ GPR174    ┆ 7.472695  ┆ 7.693039  ┆ … ┆ 8.83835   ┆ 7.851796  ┆ 7.858072  ┆ 6.91692  │
│ 147138    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ FARP1     ┆ 6.940183  ┆ 7.49388   ┆ … ┆ 6.001296  ┆ 6.299561  ┆ 7.777429  ┆ 6.503437 │
│ 152767    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ C19orf76  ┆ 6.154172  ┆ 5.498171  ┆ … ┆ 5.256311  ┆ 6.059971  ┆ 6.393223  ┆ 4.967428 │
│ 224420    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
mirna = pl.read_csv("mds_data/preprocessed/mirna.csv")

OmicDataSplitter(
    df=mirna,
    annotation_cols=["miRNA"],
    y_df=y,
    n_features=200,
    n_splits=5,
    random_state=3,
    output_dir="mds_data/splits/mirna",
).process_data()

In [48]:
circrna = pl.read_csv("mds_data/preprocessed/circrna.csv")

# fill the null ids with unknown id n -> this should be added to the preprocessing before
circrna_ids = circrna["circRNA_ID"]
unknown_id = 0
for i in range(len(circrna_ids)):
    if circrna_ids[i] == None:
        circrna_ids[i] = f"unknown_id_{unknown_id}"
        unknown_id += 1
circrna = circrna.with_columns(
    pl.Series("circRNA_ID", circrna_ids)
)

ods = OmicDataSplitter(
    df=circrna,
    annotation_cols=["circRNA_ID", "GENE_ID", "GENE_TYPE", "GENE_NAME", "STRAND"],
    y_df=y,
    n_features=200,
    n_splits=5,
    random_state=3,
    output_dir="mds_data/splits/circrna",
)
ods.process_data()

[[ 8.45024723 11.30466803 10.53455241 ... 11.09063447 10.44715036
  11.20161678]
 [ 9.50236005 10.86371399 10.15371322 ... 10.50136511 10.39452646
  11.01563966]
 [ 9.2735342  11.56935656  9.2735342  ... 11.30152024  9.77534875
  11.75274602]
 ...
 [10.49776474 11.71958689 10.23492987 ... 11.23433117 10.72001461
  11.99961931]
 [10.0575871  11.16377689 10.52669629 ... 11.16377689 10.88012063
  12.00000144]
 [ 9.17708977 10.63493452  8.76288279 ... 11.34507503  9.98337618
  12.12911376]]
['hsa_circ_0001387', 'hsa_circ_0002484', 'hsa_circ_0007848', 'hsa_circ_0002711', 'hsa_circ_0000551', 'hsa_circ_0005542', 'hsa_circ_0004658', 'unknown_id_0', 'hsa_circ_0005881', 'hsa_circ_0001776', 'hsa_circ_0000211', 'hsa_circ_0002468', 'unknown_id_1', 'hsa_circ_0071185', 'unknown_id_2', 'unknown_id_3', 'hsa_circ_0004524', 'hsa_circ_0004771', 'hsa_circ_0000607', 'hsa_circ_0046760', 'hsa_circ_0001006', 'hsa_circ_0001333', 'unknown_id_4', 'hsa_circ_0019170', 'hsa_circ_0004058', 'hsa_circ_0071174', 'hsa_ci

Processing folds: 100%|██████████| 5/5 [00:38<00:00,  7.75s/fold]


In [51]:
pirna = pl.read_csv("mds_data/preprocessed/pirna.csv")

OmicDataSplitter(
    df=pirna,
    annotation_cols=["piRNA_name", "piRNA_id"],
    y_df=y,
    n_features=150,
    n_splits=5,
    random_state=3,
    output_dir="mds_data/splits/pirna",
).process_data()

[[ 8.45542275  5.56947475  5.2958623  ...  6.67494918 18.6346163
  11.93145659]
 [ 9.37331964  7.20165321  7.32284885 ...  6.70323076 18.91790228
  10.79516624]
 [ 9.0753424   6.19631102  6.1150057  ...  6.66472286 18.63644873
  11.38865747]
 ...
 [ 8.13573063  6.29115214  7.41039954 ...  6.92836094 18.59323893
  11.52812814]
 [ 8.93068584  6.59591563  5.5479645  ...  7.58843909 18.6691824
  11.87951857]
 [12.19174384  7.59227334  8.33926107 ...  8.03773732 17.56803802
  13.79078395]]
['hsa_piR_020485', 'hsa_piR_013624', 'hsa_piR_008488', 'hsa_piR_014629', 'hsa_piR_020008', 'hsa_piR_000651', 'hsa_piR_001184', 'hsa_piR_007635', 'hsa_piR_000775', 'hsa_piR_001318', 'hsa_piR_002485', 'hsa_piR_020381', 'hsa_piR_016926', 'hsa_piR_018849', 'hsa_piR_015249', 'hsa_piR_019675', 'hsa_piR_000753', 'hsa_piR_014620', 'hsa_piR_018573', 'hsa_piR_019324', 'hsa_piR_001169', 'hsa_piR_016659', 'hsa_piR_001356', 'hsa_piR_016735', 'hsa_piR_020490', 'hsa_piR_019420', 'hsa_piR_014923', 'hsa_piR_000552', 'hsa_

Processing folds: 100%|██████████| 5/5 [00:12<00:00,  2.47s/fold]


In [54]:
te = pl.read_csv("mds_data/preprocessed/te_counts.csv")
te

OmicDataSplitter(
    df=te,
    annotation_cols=["TE"],
    y_df=y,
    n_features=200,
    n_splits=5,
    random_state=3,
    output_dir="mds_data/splits/te_counts",
).process_data()

[[2.58399931 1.74808202 3.4490177  ... 5.71199936 8.2671351  6.29611433]
 [3.92374007 1.88044366 2.88811289 ... 6.01272797 8.28253309 6.55077555]
 [3.38226427 2.52253091 2.07551866 ... 5.13320406 7.79503833 5.70678332]
 ...
 [4.01368942 1.69052926 4.11576908 ... 5.67338819 8.26572606 6.06283089]
 [3.59403366 1.99370296 2.99137698 ... 5.23805625 7.96139047 6.11003081]
 [3.26458651 1.29254843 4.10318847 ... 5.60539548 8.3513269  6.43936641]]
['HERV-K14CI', 'MER67D', 'MIR3', 'HERVK11DI', 'MER41G', 'AluYd2', 'LTR43_I', 'MER57F', 'LTR43B', 'LTR47B2', 'LTR59', 'L1P4c_5end', 'HERVH', 'LTR7A', 'MER92B', 'LTR1C3', 'LTR62', 'ERV3-16A3_I', 'LTR30', 'LTR44', 'MER66B', 'LTR38A1', 'LTR38', 'MLT2F', 'AluYe2', 'LTR1B0', 'PABL_B', 'MER89', 'LTR1F1', 'LTR77', 'LTR38B', 'MER57C2', 'LTR26B', 'LTR34', 'LOR1b_LTR', 'MER50C', 'LTR64', 'LTR26E', 'MER50B', 'L2B', 'LTR22', 'MER34A', 'MER57C1', 'MER34', 'LTR1C1', 'MLT1E', 'HERVK13I', 'MLT1H2', 'MER51D', 'LTR60B', 'MER66D', 'LTR1B', 'L1M3C_5', 'MER101B', 'AluSx1'

Processing folds: 100%|██████████| 5/5 [00:32<00:00,  6.52s/fold]


In [17]:
A = np.eye(3)
A[0,0] = 2
A[0,1] = 3
print(A)
A.max(axis=0)

[[2. 3. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([2., 3., 1.])

In [21]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=3)

list(skf.split(np.zeros(len(y)), y["class"]))

[(array([ 0,  1,  2,  3,  6,  8,  9, 10, 13, 14, 15, 16, 17, 18, 19, 20, 21,
         23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 37, 38, 39, 40, 41, 43,
         45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 63,
         64]),
  array([ 4,  5,  7, 11, 12, 22, 24, 34, 36, 42, 44, 46, 62, 65])),
 (array([ 0,  1,  2,  4,  5,  7,  8, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21,
         22, 23, 24, 25, 26, 27, 28, 29, 30, 33, 34, 35, 36, 37, 38, 39, 40,
         41, 42, 43, 44, 45, 46, 48, 50, 52, 53, 54, 56, 57, 58, 59, 60, 61,
         62, 65]),
  array([ 3,  6,  9, 10, 15, 31, 32, 47, 49, 51, 55, 63, 64])),
 (array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 18,
         22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 40, 42, 43,
         44, 45, 46, 47, 48, 49, 51, 52, 54, 55, 57, 58, 59, 60, 61, 62, 63,
         64, 65]),
  array([ 0, 17, 19, 20, 21, 23, 37, 38, 39, 41, 50, 53, 56])),
 (array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 1

In [29]:
from src.data_splitting import OmicDataSplitter

ods = OmicDataSplitter(y, n_splits=5, random_state=3)

In [28]:
mrna = pl.read_csv("mds_data/preprocessed/mrna.csv")
mrna

shape: (3_000, 68)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ GENE_ID   ┆ GENE_NAME ┆ N58       ┆ N60       ┆ … ┆ V839      ┆ V883      ┆ V888      ┆ V940     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ENSG00000 ┆ SEC14L5   ┆ 4.574155  ┆ 7.288239  ┆ … ┆ 3.976603  ┆ 5.670529  ┆ 4.456624  ┆ 4.897539 │
│ 103184    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ LGALSL    ┆ 7.455039  ┆ 8.479401  ┆ … ┆ 6.838144  ┆ 7.450425  ┆ 6.055094  ┆ 6.88753  │
│ 119862    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ IGFBP5    ┆ 1.531313  ┆ 4.93984   ┆ … ┆ 2.710774  ┆ 4.358541  ┆ 5.20171   ┆ 6.416449 │
│ 115461    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ THBS1     ┆ 10.787846 ┆ 12.452547 ┆ … ┆ 10.274893 ┆ 10.805033 ┆ 10.464737 ┆ 10.70489 │
│ 137801    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ ENSG00000 ┆ HPSE      ┆ 6.935416  ┆ 7.987946  ┆ … ┆ 7.451146  ┆ 6.940394  ┆ 6.860065  ┆ 6.735584 │
│ 173083    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ENSG00000 ┆ RBFOX2    ┆ 8.22931   ┆ 8.577745  ┆ … ┆ 7.52732   ┆ 7.067754  ┆ 7.545361  ┆ 6.655649 │
│ 100320    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ EPS8L1    ┆ 4.921367  ┆ 5.092288  ┆ … ┆ 4.054711  ┆ 4.791207  ┆ 4.437371  ┆ 4.463407 │
│ 131037    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ GPR174    ┆ 7.472695  ┆ 7.693039  ┆ … ┆ 8.83835   ┆ 7.851796  ┆ 7.858072  ┆ 6.91692  │
│ 147138    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ FARP1     ┆ 6.940183  ┆ 7.49388   ┆ … ┆ 6.001296  ┆ 6.299561  ┆ 7.777429  ┆ 6.503437 │
│ 152767    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ C19orf76  ┆ 6.154172  ┆ 5.498171  ┆ … ┆ 5.256311  ┆ 6.059971  ┆ 6.393223  ┆ 4.967428 │
│ 224420    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [30]:
ods.process_data(
    mrna,
    "mds_data/splits/mrna",
    annotation_cols=["GENE_ID", "GENE_NAME"],
    normalization="minmax",
    feature_selection="mrmr",
    n_features=50,
)

TypeError: DataFrame.__init__() got an unexpected keyword argument 'columns'