# Feature selection and data splitting for mds data 

In [1]:
import numpy as np
import polars as pl
from sklearn.model_selection import StratifiedKFold

In [2]:
y = pl.read_csv("mds_data/preprocessed/annotations_66.csv")

y = (
    y.select("SAMPLE_ID", "disease")
    .rename({"SAMPLE_ID": "sample_ids", "disease": "class"})
    .with_columns(pl.col("class") - 1)
)
y

shape: (66, 2)
┌────────────┬───────┐
│ sample_ids ┆ class │
│ ---        ┆ ---   │
│ str        ┆ i64   │
╞════════════╪═══════╡
│ N58        ┆ 0     │
│ N60        ┆ 0     │
│ N70        ┆ 0     │
│ N82        ┆ 0     │
│ N83        ┆ 0     │
│ …          ┆ …     │
│ V806       ┆ 1     │
│ V839       ┆ 1     │
│ V883       ┆ 1     │
│ V888       ┆ 1     │
│ V940       ┆ 1     │
└────────────┴───────┘

In [3]:
mrna = pl.read_csv("mds_data/preprocessed/mrna.csv")
mrna

shape: (3_000, 68)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ GENE_ID   ┆ GENE_NAME ┆ N58       ┆ N60       ┆ … ┆ V839      ┆ V883      ┆ V888      ┆ V940     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ENSG00000 ┆ SEC14L5   ┆ 4.574155  ┆ 7.288239  ┆ … ┆ 3.976603  ┆ 5.670529  ┆ 4.456624  ┆ 4.897539 │
│ 103184    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ LGALSL    ┆ 7.455039  ┆ 8.479401  ┆ … ┆ 6.838144  ┆ 7.450425  ┆ 6.055094  ┆ 6.88753  │
│ 119862    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ IGFBP5    ┆ 1.531313  ┆ 4.93984   ┆ … ┆ 2.710774  ┆ 4.358541  ┆ 5.20171   ┆ 6.416449 │
│ 115461    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ THBS1     ┆ 10.787846 ┆ 12.452547 ┆ … ┆ 10.274893 ┆ 10.805033 ┆ 10.464737 ┆ 10.70489 │
│ 137801    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ ENSG00000 ┆ HPSE      ┆ 6.935416  ┆ 7.987946  ┆ … ┆ 7.451146  ┆ 6.940394  ┆ 6.860065  ┆ 6.735584 │
│ 173083    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ENSG00000 ┆ RBFOX2    ┆ 8.22931   ┆ 8.577745  ┆ … ┆ 7.52732   ┆ 7.067754  ┆ 7.545361  ┆ 6.655649 │
│ 100320    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ EPS8L1    ┆ 4.921367  ┆ 5.092288  ┆ … ┆ 4.054711  ┆ 4.791207  ┆ 4.437371  ┆ 4.463407 │
│ 131037    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ GPR174    ┆ 7.472695  ┆ 7.693039  ┆ … ┆ 8.83835   ┆ 7.851796  ┆ 7.858072  ┆ 6.91692  │
│ 147138    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ FARP1     ┆ 6.940183  ┆ 7.49388   ┆ … ┆ 6.001296  ┆ 6.299561  ┆ 7.777429  ┆ 6.503437 │
│ 152767    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ C19orf76  ┆ 6.154172  ┆ 5.498171  ┆ … ┆ 5.256311  ┆ 6.059971  ┆ 6.393223  ┆ 4.967428 │
│ 224420    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
from src.data_preprocessing import OmicDataSplitter

ods = OmicDataSplitter(
    df=mrna,
    annotation_cols=["GENE_ID", "GENE_NAME"],
    y_df=y,
    n_splits=5,
    random_state=3,
    output_dir="mds_data/splits/mrna",
)
ods.process_data()

In [17]:
A = np.eye(3)
A[0,0] = 2
A[0,1] = 3
print(A)
A.max(axis=0)

[[2. 3. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([2., 3., 1.])

In [21]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=3)

list(skf.split(np.zeros(len(y)), y["class"]))

[(array([ 0,  1,  2,  3,  6,  8,  9, 10, 13, 14, 15, 16, 17, 18, 19, 20, 21,
         23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 37, 38, 39, 40, 41, 43,
         45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 63,
         64]),
  array([ 4,  5,  7, 11, 12, 22, 24, 34, 36, 42, 44, 46, 62, 65])),
 (array([ 0,  1,  2,  4,  5,  7,  8, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21,
         22, 23, 24, 25, 26, 27, 28, 29, 30, 33, 34, 35, 36, 37, 38, 39, 40,
         41, 42, 43, 44, 45, 46, 48, 50, 52, 53, 54, 56, 57, 58, 59, 60, 61,
         62, 65]),
  array([ 3,  6,  9, 10, 15, 31, 32, 47, 49, 51, 55, 63, 64])),
 (array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 18,
         22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 40, 42, 43,
         44, 45, 46, 47, 48, 49, 51, 52, 54, 55, 57, 58, 59, 60, 61, 62, 63,
         64, 65]),
  array([ 0, 17, 19, 20, 21, 23, 37, 38, 39, 41, 50, 53, 56])),
 (array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 1

In [29]:
from src.data_splitting import OmicDataSplitter

ods = OmicDataSplitter(y, n_splits=5, random_state=3)

In [28]:
mrna = pl.read_csv("mds_data/preprocessed/mrna.csv")
mrna

shape: (3_000, 68)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ GENE_ID   ┆ GENE_NAME ┆ N58       ┆ N60       ┆ … ┆ V839      ┆ V883      ┆ V888      ┆ V940     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ENSG00000 ┆ SEC14L5   ┆ 4.574155  ┆ 7.288239  ┆ … ┆ 3.976603  ┆ 5.670529  ┆ 4.456624  ┆ 4.897539 │
│ 103184    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ LGALSL    ┆ 7.455039  ┆ 8.479401  ┆ … ┆ 6.838144  ┆ 7.450425  ┆ 6.055094  ┆ 6.88753  │
│ 119862    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ IGFBP5    ┆ 1.531313  ┆ 4.93984   ┆ … ┆ 2.710774  ┆ 4.358541  ┆ 5.20171   ┆ 6.416449 │
│ 115461    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ THBS1     ┆ 10.787846 ┆ 12.452547 ┆ … ┆ 10.274893 ┆ 10.805033 ┆ 10.464737 ┆ 10.70489 │
│ 137801    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ ENSG00000 ┆ HPSE      ┆ 6.935416  ┆ 7.987946  ┆ … ┆ 7.451146  ┆ 6.940394  ┆ 6.860065  ┆ 6.735584 │
│ 173083    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ENSG00000 ┆ RBFOX2    ┆ 8.22931   ┆ 8.577745  ┆ … ┆ 7.52732   ┆ 7.067754  ┆ 7.545361  ┆ 6.655649 │
│ 100320    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ EPS8L1    ┆ 4.921367  ┆ 5.092288  ┆ … ┆ 4.054711  ┆ 4.791207  ┆ 4.437371  ┆ 4.463407 │
│ 131037    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ GPR174    ┆ 7.472695  ┆ 7.693039  ┆ … ┆ 8.83835   ┆ 7.851796  ┆ 7.858072  ┆ 6.91692  │
│ 147138    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ FARP1     ┆ 6.940183  ┆ 7.49388   ┆ … ┆ 6.001296  ┆ 6.299561  ┆ 7.777429  ┆ 6.503437 │
│ 152767    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ C19orf76  ┆ 6.154172  ┆ 5.498171  ┆ … ┆ 5.256311  ┆ 6.059971  ┆ 6.393223  ┆ 4.967428 │
│ 224420    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [30]:
ods.process_data(
    mrna,
    "mds_data/splits/mrna",
    annotation_cols=["GENE_ID", "GENE_NAME"],
    normalization="minmax",
    feature_selection="mrmr",
    n_features=50,
)

TypeError: DataFrame.__init__() got an unexpected keyword argument 'columns'